# Generated by Django 2.2 on 2020-07-15 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('server_ip', models.CharField(max_length=20)),
                ('port', models.IntegerField()),
                ('request_count', models.IntegerField()),
                ('all_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_count', models.IntegerField()),
                ('client_ip', models.CharField(max_length=20)),
                ('request_time', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table', to='platForm.UserInfo')),
            ],
        ),
    ]
